name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my_image
    - name: Build and Push RUN docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: megharaj1006/test
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v2
      with:
        tags: my_image:latest
        push: false
  #  - uses: addnab/docker-run-action@v3
   #   with:
    #    image: my_image:latest
     #   run: echo "hello world"

    - uses: addnab/docker-run-action@v3
      with:
        tags: my_image:latest
        run: docker run --tag my_image
   # - name: Run the docker image
   #   run: docker run my_image:latest
